### ISSUE TITLE
Nginx-formatter cannot work properly with nginx.conf hint at the same time

### ISSUE THREAD

**Issue by sunrishe** [raynigon/vscode-nginx-formatter#35]
VSCODE Version: 1.49.1
nginx-formatter Version: v0.0.10
nginx.conf hint Version: v0.1.0
I installed nginx-formatter and nginx.conf prompt together in vscode, and opened the nginx.conf file. There are NGINX and NGINX Conf in language mode. It can be formatted in NGINX mode, but the syntax cannot be highlighted. In NGINX Conf mode, the related functions prompted by nginx.conf can be used normally, but the file format cannot be executed. Please solve this problem.

**Comment by olvina** [comment]
@sunrishe same for me. 

Extension documentation says: 
1. Open a Document
2. Make sure the File Association is set to NGINX

However, when .conf file associations is set to NGINX (all uppercase) extension doesn't work, but when in lowercase it does.

It is best to be set in uppercase as that will make nginx.conf hint work as well.

**Comment by raynigon** [comment]
Released with v0.0.11

**Comment by ahmadalli** [comment]
there's an issue with `hangxingliu.vscode-nginx-conf-hint` language definition: it uses `NGINX` as `id` for the language instead of `nginx`. This makes it impossible to both extension on the same file. Since the project looks abandoned, I created my own fork and fixed the problem there:
https://github.com/ahmadalli/vscode-nginx-conf

**Comment by raynigon** [comment]
@ahmadalli This will be fixed in Release v0.0.12

**Comment by sunrishe** [comment]
@raynigon @ahmadalli Thank you for your kind help, raynigon.nginx-formatter+ahmadalli.vscode-nginx-conf is perfect!
